server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SS
    username: SS
    password: SS
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update

# App Properties
flashSchool:
  app:
    jwtSecret: 5Xz3Pb8+fttP9V1phnx5hOqWzHj2fFg14jSt+zBQquOe2c0qGZ7m+NqzNH5sDhq1zqD1+8Am00uP7XujMxw5yDsg8Rh3yPppT2yAl4h0eEOB2LZZnLQDb3ZPz3Jt5g==
    jwtExpirationMs: 86400000

