server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.wauruqdnimihwjwcmijg
    password: woDloynssshhIIfv
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      time_zone: Europe/Istanbul
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB
  http:
    multipart:
      enabled: true
  cache:
    jcache:
      config:
        classpath: ehcache.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: infostumy@gmail.com
    password: ilebdcfoujfeitgq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Europe/Istanbul
# App Properties
management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled:  true
  flashSchool:
    app:
      jwtSecret: 5Xz3Pb8+fttP9V1phnx5hOqWzHj2fFg14jSt+zBQquOe2c0qGZ7m+NqzNH5sDhq1zqD1+8Am00uP7XujMxw5yDsg8Rh3yPppT2yAl4h0eEOB2LZZnLQDb3ZPz3Jt5g==
      jwtExpirationMs: 86400000
      mailAddress: flashschool86@gmail.com

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: debug
        tool:
          hbm2ddl: debug
info:
  application:
    name: 'Stumy Backend App'
    description: 'This is Stumy Backend Project'
    version: '@project.version@'