server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.wauruqdnimihwjwcmijg
    password: woDloynssshhIIfv
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  http:
    multipart:
      enabled: true
  cache:
    jcache:
      config:
        classpath: ehcache.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: infostumy@gmail.com
    password: ilebdcfoujfeitgq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Europe/Istanbul

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 440255479092-ugbb4o44j84fjjepdl97dr7c7qo5fjms.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8081/login/oauth2/code/google

# App Properties
management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  flashSchool:
    app:
      jwtSecret: 5Xz3Pb8+fttP9V1phnx5hOqWzHj2fFg14jSt+zBQquOe2c0qGZ7m+NqzNH5sDhq1zqD1+8Am00uP7XujMxw5yDsg8Rh3yPppT2yAl4h0eEOB2LZZnLQDb3ZPz3Jt5g==
      jwtExpirationMs: 2592000000
      mailAddress: infostumy@gmail.com

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: debug
        tool:
          hbm2ddl: debug
info:
  application:
    name: 'Stumy Backend App'
    description: 'This is Stumy Backend Project'
    version: '@project.version@'

supabase:
  api:
    url: https://wauruqdnimihwjwcmijg.supabase.co/storage/v1/s3
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhdXJ1cWRuaW1paHdqd2NtaWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NDk5NDcsImV4cCI6MjA1MjAyNTk0N30.bvdBKTPaBekKm1qx3tr8JepbKyUa5V_ug4UDk8BlJ5c


cloud:
  aws:
    credentials:
      access-key: AKIAZ5TC5E2FUKITOOO5
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: stumystorage
    url: https://stumystorage.s3.eu-north-1.amazonaws.com/  # burada tutulacak
    cdn: https://d2c7jt33cnh7in.cloudfront.net/             # buradan Ã§ekilecek